variables:
  # fix for old git version
  GIT_STRATEGY: clone
  GIT_SSL_NO_VERIFY: "true"
  # config Maven
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=/cache/.m2/repository"
  # config SonarQube
  SONAR_MAVEN_GOAL: org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar
  SONAR_USER_HOME: /cache/sonar
  # config Nexus IQ server
  CLM_MAVEN_GOAL: com.sonatype.clm:clm-maven-plugin:2.12.1:evaluate
  CLM_SERVER_ID: clm_server
  CLM_APPLICATION_ID: enu-mediation

default:
  tags:
    - 'for:application-project'
    - 'host:restricted-container'
    - 'net:soca-dev'
  image:
  #   DOCKER_IMAGE: $DOCKER_URL/ch/ge/cti/build/alpine-maven-git-node:6
    name: $DOCKER_URL/ch/ge/cti/build/docker-npm-maven:1.0.1

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - /cache/.m2/repository

stages:
  - build
  - release

clm_master:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean $CLM_MAVEN_GOAL
      -Dclm.applicationId=$CLM_APPLICATION_ID -Dclm.serverUrl=$CLM_URL -Dclm.serverId=$CLM_SERVER_ID
  when: manual

deploy_master:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean deploy $SONAR_MAVEN_GOAL
      -Dsonar.host.url=$SonarQube_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.gitlab.project_id=$CI_PROJECT_PATH
      -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
  only:
    - master

release_master:
  stage: release
  image: $DOCKER_URL/ch/ge/afc/afc-maven-multi-jdk:soca-jdk11-2
  before_script:
    - echo "=========Openshift runner specific script=========="
    - user_id=$(id -u)
    - line_content="${USER_NAME:-default}:x:$user_id:0:${USER_NAME:-default} user:${HOME}:/bin/bash"
    - echo "$line_content" >> /etc/passwd
    - pwd
    - ls -hal ./
  script:
    - git config --global user.email "$RUNNER_EMAIL"
    - git config --global user.name "$RUNNER_USERNAME"
    - git checkout $CI_COMMIT_REF_NAME
    - mvn $MAVEN_CLI_OPTS release:prepare release:perform
      -Dresume=false
      -DignoreSnapshots=true
      -Dusername=$GITLAB_USER -Dpassword=$GITLAB_PASSWORD
      -DscmCommentPrefix="[skip ci] "
      -Darguments="-DskipTests -Dmaven.javadoc.skip=true"
  artifacts:
    paths:
      - target/*.war
  when: manual
