variables:
  # fix for old git version
  GIT_STRATEGY: clone
  GIT_SSL_NO_VERIFY: "true"
  # Proxy OCSIN
  HTTP_PROXY: 'http://***REMOVED***'
  HTTPS_PROXY: 'http://***REMOVED***'
  NO_PROXY: 'localhost,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,10.145.38.211,.***REMOVED***,***REMOVED***'
  # config Maven
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=/cache/.m2/repository"
  # config SonarQube
  SONAR_MAVEN_GOAL: org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar
  SONAR_USER_HOME: /cache/sonar
  # config Nexus IQ server
  CLM_MAVEN_GOAL: com.sonatype.clm:clm-maven-plugin:2.12.1:evaluate
  CLM_SERVER_ID: clm_server
  CLM_APPLICATION_ID: enu-mediation
  #   DOCKER_IMAGE: ***REMOVED***/ch/ge/cti/build/alpine-maven-git-node:6

default:
  tags:
    - 'for:application-project'
    - 'host:restricted-container'
    - 'net:soca-dev'
  image:
    name: $DOCKER_URL/ch/ge/cti/build/docker-npm-maven:1.0.1

stages:
#  - build
  - deploy
  - release

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - /cache/.m2/repository

#build_and_analyse_sonarqube_master:
#  stage: build
#  script:
#    - mvn $MAVEN_CLI_OPTS clean verify $SONAR_MAVEN_GOAL -Dsonar.host.url=$SonarQube_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.max_blocker_issues_gate=-1 -Dsonar.gitlab.max_critical_issues_gate=-1
#  only:
#  - master
#
#build_on_and_analyse_sonarqube_preview:
#  stage: build
#  script:
#    - mvn $MAVEN_CLI_OPTS clean verify $SONAR_MAVEN_GOAL -Dsonar.host.url=$SonarQube_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.max_blocker_issues_gate=-1 -Dsonar.gitlab.max_critical_issues_gate=-1 -Dsonar.gitlab.unique_issue_per_inline=true -Dsonar.branch.name=$CI_COMMIT_REF_NAME
#  only:
#  - master
#
#analyse_clm_master:
#  stage: build
#  script:
#    - mvn $MAVEN_CLI_OPTS $CLM_MAVEN_GOAL -Dclm.applicationId=$CLM_APPLICATION_ID -Dclm.serverUrl=$CLM_URL -Dclm.serverId=$CLM_SERVER_ID
#  only:
#    - master

deploy_master:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS clean deploy -DskipTests
  only:
    - master

release_master:
  stage: release
  image: $DOCKER_URL/ch/ge/afc/afc-maven-multi-jdk:soca-jdk11-2
  before_script:
    - echo "=========Openshift runner specific script=========="
    - user_id=$(id -u)
    - line_content="${USER_NAME:-default}:x:$user_id:0:${USER_NAME:-default} user:${HOME}:/bin/bash"
    - echo "$line_content" >> /etc/passwd
    - pwd
    - ls -hal ./
  script:
    - git config --global user.email "$RUNNER_EMAIL"
    - git config --global user.name "$RUNNER_USERNAME"
    - git checkout $CI_COMMIT_REF_NAME
    - mvn $MAVEN_CLI_OPTS release:prepare release:perform -DscmCommentPrefix='[skip ci] ' -Dresume=false -Darguments="-DskipTests -Dmaven.javadoc.skip=true" -DignoreSnapshots=true -Dusername=$GITLAB_USER -Dpassword=$GITLAB_PASSWORD
  artifacts:
    paths:
      - target/*.war
  when: manual
