variables:
  # fix for old git version
  GIT_STRATEGY: clone
  GIT_SSL_NO_VERIFY: "true"
  # config Maven
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=/cache/.m2/repository"
  # config SonarQube
  SONAR_MAVEN_GOAL: org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar
  SONAR_USER_HOME: /cache/sonar
  # config CLM
  #CLM_MAVEN_GOAL: com.sonatype.clm:clm-maven-plugin:2.12.1:evaluate
  #CLM_SERVER_ID: clm_server
  #CLM_APPLICATION_ID: enu-mediation

stages:
  - build
  - deploy
  - release

build_and_sonarqube_preview:
  stage: build
  image: $DOCKER_URL/ch/ge/cti/build/docker-npm-maven:1.0.1
  script:
    - npm config set cache /cache/npm
    - mvn $MAVEN_CLI_OPTS install $SONAR_MAVEN_GOAL -Dsonar.host.url=$SonarQube_URL -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$(git log --pretty=format:%H origin/master..$CI_COMMIT_SHA | tr '\n' ',') -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.unique_issue_per_inline=true -Dsonar.gitlab.max_blocker_issues_gate=-1 -Dsonar.gitlab.max_critical_issues_gate=-1
  except :
    - master

analyse_sonar_master:
  stage: build
  image: $DOCKER_URL/ch/ge/cti/build/docker-npm-maven:1.0.1
  script:
    - npm config set cache /cache/npm
    - mvn $MAVEN_CLI_OPTS verify $SONAR_MAVEN_GOAL -Dsonar.host.url=$SonarQube_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.max_blocker_issues_gate=-1 -Dsonar.gitlab.max_critical_issues_gate=-1
#  only:
  except:
    - master

analyse_clm_master:
  stage: build
  image: $DOCKER_URL/ch/ge/cti/build/docker-npm-maven:1.0.1
  script:
    - npm config set cache /cache/npm
    - mvn $MAVEN_CLI_OPTS $CLM_MAVEN_GOAL -Dclm.applicationId=$CLM_APPLICATION_ID -Dclm.serverUrl=$CLM_URL -Dclm.serverId=$CLM_SERVER_ID
#  only:
  except:
    - master

deploy_master:
  stage: deploy
  image: $DOCKER_URL/ch/ge/cti/build/docker-npm-maven:1.0.1
  script:
    - npm config set cache /cache/npm
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master

release_master:
  stage: release
  image: $DOCKER_URL/ch/ge/cti/build/docker-npm-maven:1.0.1
  script:
    - npm config set cache /cache/npm
    - mvn $MAVEN_CLI_OPTS -Dresume=false release:prepare release:perform
  when: manual
