app:
  formsolution:
    host: ***REMOVED***
    ***REMOVED***
    path: aelportalenu/formservices/rest

server:
  port: 8666

camel:
  springboot:
    main-run-controller: false
    message-history: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true
      object-mapper: json-jackson
      content-type-header: true
      pretty-print: false
      timezone: CET
      use-list: false
      use-default-object-mapper: false
  component:
    rabbitmq:
      hostname: ***REMOVED***
      ***REMOVED***
      password***REMOVED***
      username***REMOVED***
      skip-exchange-declare: true
      skip-queue-bind: true
      skip-queue-declare: true
    http:
      use-global-ssl-context-parameters: true
    servlet:
      mapping:
        context-path: /api/*
  ssl:
    config:
      key-managers:
        key-password: "password"
        key-store:
          resource: "security/lab.jks"
          password: "password"
          type: "jks"
      trust-managers:
        key-store:
          resource: "security/lab.jks"
          password: "password"
          type: "jks"

logging:
  level:
    root: INFO
    org:
      apache:
        camel: INFO
      springframework: ERROR
