app:
  formservices:
    url: ${FORMSERVICES_BASEURL}/rest
    ssl:
      trust-store:
        resource: classpath:security/gina.20191003.jks
        password: ${SSL_TRUSTSTORE_PASS}
  logging:
    max-file-content-size: '100'
  document:
    mime-types: application/pdf
  rabbitmq:
    dlx: enu-to-all-dead-letter-x # Exchange où on écrit les messages en erreur
    queue-in: all-to-enu-q # queue où on lit les messages des SI métier
    exchange-out: enu-to-all-x # Exchange d'envoi des messages aux SI métier

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: '5672'
    virtual-host: aelenu
    ssl:
      verify-hostname: false
      trust-store: classpath:security/gina.20191003.jks
      trust-store-password: ${SSL_TRUSTSTORE_PASS}
      enabled: true
    listener:
      direct:
        acknowledge-mode: auto
  security:
    oauth2:
      client:
        provider:
          sso:
            issuer-uri: ${RABBITMQ_UAA}
        registration:
          sso:
            client-id: ${UAA_CLIENT_ID}
            client-secret: ${UAA_CLIENT_SECRET}
            username: ${UAA_USERNAME}
            password: ${UAA_PASSWORD}
            authorization-grant-type: password

logging:
  level:
    root: INFO
    org.apache.camel: INFO
    org.springframework: ERROR
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
